# Paper-aligned noise model (channels + GPT) parameters.
# Tune these to match a specific device calibration; structure matches the paper.

cycle_ns: 1100.0
T1_us: 68.0
Tphi_us: 89.0
p_heat: 0.0

# Readout / reset
p_readout: 0.003
p_reset: 0.003

# DQLR transition probs on |0>,|1>,|2> (rows sum to 1)
dqlr_matrix:
  - [1.0, 0.0, 0.0]
  - [0.0, 1.0, 0.0]
  - [0.05, 0.90, 0.05]

# CZ related mechanisms
p_cz_leak_11_to_02: 0.001
p_cz_crosstalk_ZZ: 0.0005
p_cz_swap_like: 0.0005
p_leak_transport_12_to_30: 0.0005

# Residual (“excess”) errors
p_1q_excess: 0.0005
p_cz_excess: 0.0010
p_idle_excess: 0.0005

# Injection controls
twirl_idles_each_tick: false
twirl_after_1q_gates: true
